Repository adarsh-singh01/VaultChain, pull requests merged in 2024-11, with the labels that each got.

#18 Create LICENSE
  LICENSE
Labels: documentation, level2

#22 Create SECURITY.md
  SECURITY.md
Labels: documentation, gssoc, level2

#24 Added code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc-ext, level2

#25 Added all contributors to readme
  README.md
Labels: documentation, enhancement, level3, gssoc-ext

#23 Added Contributing file
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, level2

#26 enhanced readme
  README.md
Labels: documentation, gssoc-ext, level1

#27 added issues
  ISSUES.md
Labels: documentation, gssoc-ext, level2

#28 added learn md
  LEARN.md
Labels: documentation, gssoc-ext, level2
